// pages/shhh.tsx
import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';

const videoCount = 8;

const videos = Array.from(
    Array(videoCount),
    (_, x) => `./video/${x + 1}.mp4`
);

const Shhh: NextPage = () => {
    const [videoIndex, setVideoIndex] = useState<number>(null);

    const dynamicRoute = useRouter().asPath;

    useEffect(() => {
        let newIndex = videoIndex;
        console.log(videos)

        while (newIndex == videoIndex) {
            newIndex = Math.floor(Math.random() * videos.length);
        }

        setVideoIndex(newIndex);
    }, [dynamicRoute]);

    return (
        <React.Fragment>
            <h1 className="text-3xl heading">
                You have found the <span className="rainbow">treasure</span>
            </h1>

            <span className="subheading text-xl">Enjoy this video as a reward (:</span>

            <br />

            <span className='subheading text-sm'>Video {videoIndex + 1}/{videoCount}</span>

            <div className="flex justify-center mt-10">
                <video src={videos[videoIndex]} height={500} width={500} autoPlay loop controls></video>
            </div>
        </React.Fragment>
    );
};

export default Shhh;

// src/routes/shhh/+page.svelte
<script lang="ts">
    import Typewriter from "$lib/Typewriter.svelte";
    import { onMount } from "svelte";
	import IconButton from '$lib/IconButton.svelte';
    import { faArrowLeft, faArrowRight, faShuffle } from "@fortawesome/free-solid-svg-icons";

	const videoCount = 8;
	let origin: string;

	$: number = 0;

	const randomiseVideo = () => {
		let newNumber = number;
		
		while (newNumber === number) {
			newNumber = 1 + Math.floor(Math.random() * (videoCount - 1)); // 1-8
		}

		number = newNumber;
	}

	const previousVideo = () => {
		number -= 1;

		if (number <= 0) {
			number = videoCount;
		}
	}
	
	const nextVideo = () => number = number % videoCount + 1;

	onMount(() => {
		origin = window.location.origin;
		randomiseVideo();
	});
</script>

<Typewriter>
	<h1>You found the treasure!</h1>
</Typewriter>

<h2>Now enjoy this video, you deserve it (:</h2>

<a href={`${origin}/shhh/${number}.mp4`} download>
	<h3 class='my-3 hover:underline' >Video {number}/8</h3>
</a>

<div>
	<IconButton icon={faArrowLeft} action={previousVideo} iconSize='1.5x' classes='text-gray-600 hover:text-slate-900' />
	<IconButton icon={faShuffle} action={randomiseVideo} iconSize='1.5x' classes='text-gray-600 hover:text-slate-900' />
	<IconButton icon={faArrowRight} action={nextVideo} iconSize='1.5x' classes='text-gray-600 hover:text-slate-900' />
</div>

<div class="flex justify-center mt-5">
    <video src={`${origin}/shhh/${number}.mp4`} width={500} height={500} autoplay loop controls />
</div>
